databases:
  - name: school-db
    databaseName: school_management_db
    user: school_user
    region: oregon

services:
  - type: web
    name: school-management-system
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_modernized.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: school_modernized.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False" 