# Generated by Django 5.0.6 on 2025-06-24 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='School Name', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('principal_name', models.CharField(max_length=200)),
                ('principal_email', models.EmailField(max_length=254)),
                ('principal_phone', models.CharField(max_length=20)),
                ('established_date', models.DateField()),
                ('board_affiliation', models.CharField(choices=[('CBSE', 'Central Board of Secondary Education'), ('ICSE', 'Indian Certificate of Secondary Education'), ('STATE', 'State Board'), ('IB', 'International Baccalaureate'), ('IGCSE', 'International General Certificate of Secondary Education')], max_length=100)),
                ('academic_year_start_month', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfiguration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='admissionsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='admissionsession',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='building',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='building',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='admissionsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sessions', to='core.schoolsettings'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.schoolsettings'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.schoolsettings'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.schoolsettings'),
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='school',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='school',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
